# Generated by Django 4.1.7 on 2023-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='temp',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
