# Generated by Django 4.1.7 on 2023-08-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_message_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='temp',
        ),
    ]
