# Generated by Django 4.1.7 on 2023-08-09 17:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_message_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
