# Generated by Django 4.1.7 on 2023-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_message_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_name',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
