# Generated by Django 4.1.7 on 2023-07-15 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Phone')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fk_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='email key')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('skim1', models.CharField(blank=True, max_length=30, null=True, verbose_name='NN-Skim')),
                ('skim2', models.CharField(blank=True, max_length=30, null=True, verbose_name='EP-Skim')),
                ('covr1', models.CharField(blank=True, max_length=30, null=True, verbose_name='NN-Cover')),
                ('covr2', models.CharField(blank=True, max_length=30, null=True, verbose_name='EP-Cover')),
                ('group', models.CharField(blank=True, max_length=30, null=True, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Prod-Code')),
                ('prod_tag', models.CharField(blank=True, choices=[(None, 'Select'), ('01', 'SCB'), ('02', 'TCB'), ('03', 'S-PIPE'), ('04', 'T-PIPE')], max_length=7, null=True, verbose_name='Prod-Catg')),
                ('fab_type', models.CharField(blank=True, choices=[(None, 'Select'), ('01', 'NN'), ('02', 'EP'), ('03', 'PP')], max_length=5, null=True, verbose_name='Fab-type')),
                ('fab_str', models.CharField(blank=True, choices=[(None, 'Select'), ('01', '90'), ('02', '100'), ('03', '125'), ('04', '160'), ('05', '200'), ('06', '250'), ('07', '315'), ('08', '350'), ('09', '400'), ('10', '450'), ('11', '500')], max_length=3, null=True, verbose_name='Fab-Style')),
                ('edge', models.CharField(blank=True, choices=[(None, 'Select'), ('01', 'CE'), ('02', 'ME')], max_length=5, null=True, verbose_name='Edge')),
                ('st_rating', models.CharField(blank=True, choices=[(None, 'Select'), ('ST 1000', 'ST 1000'), ('ST 1250', 'ST 1250'), ('ST 1400', 'ST 1400'), ('ST 1600', 'ST 1600'), ('ST 1800', 'ST 1800'), ('ST 2000', 'ST 2000'), ('ST 2500', 'ST 2500'), ('ST 2800', 'ST 2800'), ('ST 3150', 'ST 3150'), ('ST 3500', 'ST 3500'), ('ST 4000', 'ST 4000'), ('ST 4500', 'ST 4500'), ('ST 5000', 'ST 5000'), ('ST 5400', 'ST 5400'), ('ST 6300', 'ST 6300'), ('ST 6800', 'ST 6800'), ('ST 7500', 'ST 7500'), ('ST 2250', 'ST 2250')], max_length=7, null=True, verbose_name='Strength')),
                ('cord_const', models.CharField(blank=True, choices=[(None, 'Select'), ('01', '7x7'), ('02', '7x19')], max_length=15, null=True, verbose_name='Cord Const.')),
                ('prod_des', models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='email key')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.grade', verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salescustomer', to='product.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_des', models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Description')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width(mm)')),
                ('ply', models.IntegerField(blank=True, null=True, verbose_name='Ply(no)')),
                ('tr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Top Rubber(mm)')),
                ('br', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bot Rubber(mm)')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Bot Rubber(mm)')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockprdcode', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('perprice', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField(default=1)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesbillno', to='product.salesbill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesitem', to='product.stock')),
            ],
        ),
        migrations.CreateModel(
            name='SalesBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, max_length=50, null=True)),
                ('cess', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedetailsbillno', to='product.salesbill')),
            ],
        ),
    ]
