# Generated by Django 4.1.7 on 2023-06-23 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skim1', models.CharField(blank=True, max_length=30, null=True, verbose_name='NN-Skim')),
                ('skim2', models.CharField(blank=True, max_length=30, null=True, verbose_name='EP-Skim')),
                ('covr1', models.CharField(blank=True, max_length=30, null=True, verbose_name='NN-Cover')),
                ('covr2', models.CharField(blank=True, max_length=30, null=True, verbose_name='EP-Cover')),
                ('group', models.CharField(blank=True, max_length=30, null=True, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_tag', models.CharField(blank=True, choices=[(None, 'Select'), ('prd-1', 'SCB'), ('prd-2', 'TCB'), ('prd-3', 'S-PIPE'), ('prd-4', 'T-PIPE')], max_length=7, null=True, verbose_name='Prod-Catg')),
                ('width', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Width')),
                ('fab_type', models.CharField(blank=True, choices=[(None, 'Select'), ('fab-1', 'NN'), ('prd-2', 'EP')], max_length=5, null=True, verbose_name='Fab-type')),
                ('top_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Top Cover')),
                ('bot_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Top Cover')),
                ('edge', models.CharField(blank=True, choices=[(None, 'Select'), ('edg-1', 'CE'), ('edg-2', 'ME')], max_length=5, null=True, verbose_name='Edge')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='email key')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.grade', verbose_name='Grade')),
            ],
        ),
    ]
