# Generated by Django 4.1.7 on 2023-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='doc_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Doc.Date'),
        ),
        migrations.AddField(
            model_name='stock',
            name='doc_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Doc.No.'),
        ),
    ]
