# Generated by Django 4.1.7 on 2023-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edge',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('CE', 'CE'), ('ME', 'ME')], max_length=5, null=True, verbose_name='Edge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fab_type',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('NN', 'NN'), ('EP', 'EP')], max_length=5, null=True, verbose_name='Fab-type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_tag',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('SCB', 'SCB'), ('TCB', 'TCB'), ('S-PIPE', 'S-PIPE'), ('T-PIPE', 'T-PIPE')], max_length=7, null=True, verbose_name='Prod-Catg'),
        ),
    ]
