# Generated by Django 4.1.7 on 2023-07-15 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_stock_doc_dt_stock_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='email key'),
        ),
    ]
