# Generated by Django 4.1.7 on 2023-06-23 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_edge_alter_product_fab_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brkr_no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9)], verbose_name='No of Breaker'),
        ),
        migrations.AddField(
            model_name='product',
            name='brkr_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Breaker Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='cord_const',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('7x7', '7x7'), ('7x19', '7x19')], max_length=15, null=True, verbose_name='Cord Const.'),
        ),
        migrations.AddField(
            model_name='product',
            name='cord_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cord Dia'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_cords',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='No of Cords'),
        ),
        migrations.AddField(
            model_name='product',
            name='pitch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cord Pitch'),
        ),
        migrations.AddField(
            model_name='product',
            name='sensor_loop',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Sensor Loop'),
        ),
        migrations.AddField(
            model_name='product',
            name='st_rating',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('ST 1000', 'ST 1000'), ('ST 1250', 'ST 1250'), ('ST 1400', 'ST 1400'), ('ST 1600', 'ST 1600'), ('ST 1800', 'ST 1800'), ('ST 2000', 'ST 2000'), ('ST 2500', 'ST 2500'), ('ST 2800', 'ST 2800'), ('ST 3150', 'ST 3150'), ('ST 3500', 'ST 3500'), ('ST 4000', 'ST 4000'), ('ST 4500', 'ST 4500'), ('ST 5000', 'ST 5000'), ('ST 5400', 'ST 5400'), ('ST 6300', 'ST 6300'), ('ST 6800', 'ST 6800'), ('ST 7500', 'ST 7500'), ('ST 2250', 'ST 2250')], max_length=7, null=True, verbose_name='Strength'),
        ),
    ]
