# Generated by Django 4.1.7 on 2023-07-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_stock_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod_des',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='proddesc', to='product.product'),
            preserve_default=False,
        ),
    ]
