# Generated by Django 4.1.7 on 2023-06-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_brkr_no_product_brkr_type_product_cord_const_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_des',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Description'),
        ),
    ]
