# Generated by Django 4.1.7 on 2023-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_stock_name_alter_stock_prod_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Description'),
        ),
    ]
