# Generated by Django 4.1.7 on 2023-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_stock_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='belt_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Belt No'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Quantity(m)'),
        ),
    ]
