# Generated by Django 4.1.7 on 2023-06-25 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_grade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bot_cover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(19.0)], verbose_name='Top Cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_cover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(19.0)], verbose_name='Top Cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2500)], verbose_name='Width'),
        ),
    ]
