# Generated by Django 4.1.7 on 2023-07-19 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_stock_belt_no_alter_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='email',
            new_name='fk_email',
        ),
        migrations.AlterField(
            model_name='stock',
            name='br',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1.5), django.core.validators.MaxValueValidator(20.0)], verbose_name='Bot Rubber(mm)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ply',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)], verbose_name='Ply(no)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(450.0)], verbose_name='Quantity(m)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1.5), django.core.validators.MaxValueValidator(20.0)], verbose_name='Top Rubber(mm)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='width',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1800)], verbose_name='Width(mm)'),
        ),
    ]
