# Generated by Django 4.1.7 on 2023-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_stock_belt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='prod_des',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Description'),
        ),
    ]
