# Generated by Django 4.1.7 on 2023-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_edge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bot_cover',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brkr_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brkr_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cord_dia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='no_cords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sensor_loop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_cover',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prod-Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cord_const',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('01', '7x7'), ('02', '7x19')], max_length=15, null=True, verbose_name='Cord Const.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='edge',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('01', 'CE'), ('02', 'ME')], max_length=5, null=True, verbose_name='Edge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fab_type',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('01', 'NN'), ('02', 'EP')], max_length=5, null=True, verbose_name='Fab-type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_tag',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('01', 'SCB'), ('02', 'TCB'), ('03', 'S-PIPE'), ('04', 'T-PIPE')], max_length=7, null=True, verbose_name='Prod-Catg'),
        ),
    ]
