# Generated by Django 4.1.7 on 2023-06-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_bot_cover_remove_product_brkr_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Prod-Code'),
        ),
    ]
