# Generated by Django 4.1.7 on 2023-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_salesitem_prod_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='belt_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Belt No'),
        ),
    ]
