# Generated by Django 4.1.7 on 2023-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_salesitem_belt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='item_text_content',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Description'),
        ),
    ]
