# Generated by Django 4.1.7 on 2023-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_salesitem_item_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='item_text_content',
            field=models.CharField(default=11, max_length=250, verbose_name='Item Description'),
            preserve_default=False,
        ),
    ]
