# Generated by Django 4.1.7 on 2023-07-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_salesitem_item_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='item_text_content',
            field=models.CharField(max_length=250, verbose_name='Item Des'),
        ),
    ]
