# Generated by Django 4.1.7 on 2023-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_salesitem_item_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='item_qty_content',
            field=models.CharField(default=12, max_length=250, verbose_name='Item Des'),
            preserve_default=False,
        ),
    ]
