# Generated by Django 4.1.7 on 2023-08-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_salesitem_belt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='belt_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Belt No'),
        ),
    ]
