# Generated by Django 4.1.7 on 2023-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_salesitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='billno',
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='item_qty_content',
            field=models.CharField(max_length=250, verbose_name='Item Qnty'),
        ),
    ]
