# Generated by Django 4.1.7 on 2023-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_salesitem_billno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='belt_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Belt No'),
        ),
    ]
