# Generated by Django 4.1.7 on 2023-08-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_salesitem_belt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='perprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='Rate (Rs./m)'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total(Rs./m)'),
        ),
    ]
