# Generated by Django 4.1.7 on 2023-09-07 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_salesitem_perprice_alter_salesitem_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='perprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Rate (Rs./m)'),
        ),
    ]
