# Generated by Django 4.1.7 on 2023-09-11 13:29

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_salesitem_perprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 19, 14, 30, tzinfo=datetime.timezone.utc)),

            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesitem',
            name='doc_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='doc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc.No.'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
