# Generated by Django 4.1.7 on 2023-09-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_salesitem_created_date_salesitem_doc_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='doc_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Dt.'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='doc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Docu No.'),
        ),
    ]
