# Generated by Django 4.1.7 on 2023-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_salesitem_doc_dt_alter_salesitem_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='cust_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
