# Generated by Django 4.1.7 on 2023-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_salesitem_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbilldetails',
            name='billno',
        ),
        migrations.AddField(
            model_name='salesbilldetails',
            name='doc_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Dt.'),
        ),
        migrations.AddField(
            model_name='salesbilldetails',
            name='doc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Docu No.'),
        ),
    ]
