# Generated by Django 4.1.7 on 2023-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_remove_salesbilldetails_billno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbilldetails',
            name='doc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc No.'),
        ),
        migrations.AlterField(
            model_name='salesbilldetails',
            name='po',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
