# Generated by Django 4.1.7 on 2023-09-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_salesbilldetails_doc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='doc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc No.'),
        ),
    ]
