# Generated by Django 4.1.7 on 2023-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_salesitem_doc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splicing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('doc_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc No.')),
                ('doc_dt', models.DateField(blank=True, null=True, verbose_name='Dt.')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width(mm)')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Strength')),
                ('dia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cord Dia')),
                ('nos', models.IntegerField(blank=True, null=True, verbose_name='Cord No')),
                ('pitch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cord Pitch')),
                ('tr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Top Rubber(mm)')),
                ('br', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bot Rubber(mm)')),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('brkr_pos', models.CharField(blank=True, choices=[(None, 'Select'), ('Top', 'Top'), ('Bottom', 'Bottom'), ('Both', 'Both')], max_length=15, null=True, verbose_name='Brkr Position')),
                ('splice_type', models.IntegerField(blank=True, null=True, verbose_name='Splice Type')),
                ('splice_length', models.IntegerField(blank=True, null=True, verbose_name='Splice Length')),
                ('tc_thk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='TC Thikness')),
                ('tc_length', models.IntegerField(blank=True, null=True, verbose_name='TC Length')),
                ('tc_width', models.IntegerField(blank=True, null=True, verbose_name='TC Width')),
                ('bc_thk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BC Thikness')),
                ('bc_length', models.IntegerField(blank=True, null=True, verbose_name='BC Length')),
                ('bc_width', models.IntegerField(blank=True, null=True, verbose_name='BC Width')),
                ('ic_no', models.IntegerField(blank=True, null=True, verbose_name='IC Nos')),
                ('ic_length', models.IntegerField(blank=True, null=True, verbose_name='IC Length')),
                ('ic_height', models.IntegerField(blank=True, null=True, verbose_name='IC Height')),
                ('ic_thk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IC Thikness')),
                ('sg_width', models.IntegerField(blank=True, null=True, verbose_name='SG Width')),
                ('sg_thk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SG Thikness')),
                ('sg_length', models.IntegerField(blank=True, null=True, verbose_name='SG Length')),
                ('es_width', models.IntegerField(blank=True, null=True, verbose_name='ES Width')),
                ('es_thk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ES Thikness')),
                ('es_length', models.IntegerField(blank=True, null=True, verbose_name='ES Length')),
                ('bonder_soln', models.IntegerField(blank=True, null=True, verbose_name='Bonder Solun.')),
                ('clng_soln', models.IntegerField(blank=True, null=True, verbose_name='Cleaning Solun.')),
                ('nrc_width', models.IntegerField(blank=True, null=True, verbose_name='NRC Width')),
                ('nrc_length', models.IntegerField(blank=True, null=True, verbose_name='NRC Length')),
                ('srp_width', models.IntegerField(blank=True, null=True, verbose_name='SRP Width')),
                ('srp_length', models.IntegerField(blank=True, null=True, verbose_name='SRP Length')),
                ('pol_width', models.IntegerField(blank=True, null=True, verbose_name='POL Width')),
                ('pol_length', models.IntegerField(blank=True, null=True, verbose_name='POL Length')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
