# Generated by Django 4.1.7 on 2023-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_splicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='splicing',
            name='specn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Specn.'),
        ),
    ]
