# Generated by Django 4.1.7 on 2023-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_splicing_specn'),
    ]

    operations = [
        migrations.AddField(
            model_name='splicing',
            name='bc_brk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='splicing',
            name='tc_brk',
            field=models.BooleanField(default=False),
        ),
    ]
