# Generated by Django 4.1.7 on 2023-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_splicing_bc_brk_splicing_tc_brk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splicing',
            name='brkr_pos',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('Nil', 'Nil'), ('Top', 'Top'), ('Bottom', 'Bottom'), ('Both', 'Both')], max_length=15, null=True, verbose_name='Brkr Position'),
        ),
        migrations.AlterField(
            model_name='splicing',
            name='ic_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IC Height'),
        ),
    ]
