# Generated by Django 4.1.7 on 2023-06-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.courses', verbose_name='Courses'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='intake',
            field=models.IntegerField(blank=True, null=True, verbose_name='Intake'),
        ),
        migrations.AlterField(
            model_name='student',
            name='strength',
            field=models.IntegerField(blank=True, null=True, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.fin_year', verbose_name='Fin Year'),
        ),
    ]
