# Generated by Django 4.1.7 on 2023-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_course_name_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_name',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
    ]
