# Generated by Django 4.1.7 on 2023-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_student_year_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses_name',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='faculty_name',
            field=models.CharField(default=122, max_length=10),
            preserve_default=False,
        ),
    ]
